version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data:rw
    ports:
      - '${PORT}:${PORT}'
